### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by dozmus** [PureCS/runesource#3]
Ideas:
* Run connection accepting on separate thread
* Distribute player updating between multiple threads
* Run tasks on separate thread
* Run plugins on separate thread

**Comment by lare96** [comment]
What tasks in particular are you looking to run concurrently? Also can plugin logic be safely executed on another thread? I'll gladly open a PR for this, if you're still working on it.

**Comment by dozmus** [comment]
My biggest concern is if this will make the server too complicated.
I do somewhat try to adhere to blake’s goal of simplicity.
Thats why I havent touched this yet.

**Comment by lare96** [comment]
Doing player updating concurrently won't make it complicated at all. The other things you listed might though

**Comment by dozmus** [comment]
Feel free to implement such a change, I guess we can't stay in the past forever :)
